# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'test11' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for test11
  pod 'Amplify'
  pod 'Amplify/Tools'

  pod 'AmplifyPlugins/AWSCognitoAuthPlugin'
  pod 'AmplifyPlugins/AWSAPIPlugin'

end
